In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
resultado=pd.read_csv("data/datas limpias/3/data_resultado2.csv")

In [4]:
X1=resultado.copy()
X1.drop(columns=["quiniela",'G_esp_local', 'G_esp_visitante','%_Saques_esquina_local_favor', '%_Saques_esquina_visitante_favor',
       '%_Saques_esquina_local_contra', '%_Saques_esquina_visitante_contra',
       'Árbitro_faltas_local', 'Árbitro_faltas_visitante',
       'Árbitro_amarillas_local', 'Árbitro_amarillas_visitante',
       'Árbitro_doble_amarilla_local', 'Árbitro_doble_amarilla_visitante',
       'Árbitro_roja_directa_local', 'Árbitro_roja_directa_visitante',
       'tarjetas_total_local', 'tarjetas_total_visitante',
       'Árbitro_sum_tarjetas_local', 'Árbitro_sum_tarjetas_visitante',
       'faltas_cometidas_local', 'faltas_cometidas_visitante',
       'faltas_provocadas_local', 'faltas_provocadas_visitante',
       'amarillas_cometidas_local', 'amarillas_cometidas_visitante','amarillas_provocadas_local', 'amarillas_provocadas_visitante',
       'dobles_amarillas_cometidas_local',
       'dobles_amarillas_cometidas_visitante',
       'dobles_amarillas_provocadas_local',
       'dobles_amarillas_provocadas_visitante',
       'rojas_directas_cometida_local', 'rojas_directas_cometida_visitante',
       'rojas_directas_provocadas_local',
       'rojas_directas_provocadas_visitante', 'goles_marcados_local',
       'goles_marcados_visitante', 'goles_recibidos_local',
       'goles_recibidos_visitante', 'goles_esperados_local',
       'goles_esperados_visitante', 'goles_esperados_contra_local',
       'goles_esperados_contra_visitante', 'posesion_media_local',
       'posesion_media_visitante', '%_disparos_puerta_hechos_local',
       '%_disparos_puerta_hechos_visitante',
       '%_disparos_puerta_recibidos_local',
       '%_disparos_puerta_recibidos_visitante',
       '%_pases_cruzados_hechos_local','%_pases_cruzados_hechos_visitante', '%_pases_cruzados_recibidos_local',
       '%_pases_cruzados_recibidos_visitante', 'tarjetas_cometidas_local',
       'tarjetas_cometidas_visitante', 'tarjetas_provocadas_local',
       'tarjetas_provocadas_visitante','Pases_%_local','Pases_%_visitante'],inplace=True)
Y=resultado["quiniela"]

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X1,Y,test_size=0.15,random_state=42)

In [6]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score

In [9]:
from sklearn.ensemble import RandomForestClassifier

rnd_clas = RandomForestClassifier(n_estimators=200,
                                 max_leaf_nodes=30,
                                 random_state=42)
rnd_clas.fit(X_train, Y_train)

y_pred_clas = rnd_clas.predict(X_test)
accuracy_score(Y_test, y_pred_clas)

0.6666666666666666

In [10]:
y_pred_clas

array(['1', 'X', '2', '2', '1', '1', '2', '1', '1', '1', '1', '2', '1',
       '1', '1', '2', '1', '1', '2', '1', '2', '1', '1', '1', '2', '1',
       '1', '1', '1', '1', 'X', '2', '2', '1', '1', '1', '1', '2', '1',
       '2', 'X', '1', '1', '1', '2', '1', 'X', '2'], dtype=object)

In [8]:
Y_test

167    X
230    X
25     X
63     2
9      1
110    X
186    2
143    1
244    1
224    1
90     X
76     X
82     X
240    X
172    1
119    2
202    1
77     1
55     2
104    X
203    2
211    X
198    1
139    1
42     2
213    1
297    1
33     X
73     X
183    1
75     X
5      1
168    2
157    1
300    1
78     1
176    X
284    2
222    1
84     2
7      X
193    X
285    1
281    2
46     2
3      X
260    X
194    2
Name: quiniela, dtype: object

In [9]:
rnd_clas.predict_proba(X_test)

array([[0.42818752, 0.37696442, 0.19484805],
       [0.31898267, 0.28427346, 0.39674387],
       [0.22686293, 0.46529882, 0.30783825],
       [0.10669084, 0.68435742, 0.20895175],
       [0.83007799, 0.05415099, 0.11577102],
       [0.60394802, 0.15501287, 0.24103911],
       [0.11343428, 0.71235691, 0.17420881],
       [0.74495921, 0.10471569, 0.1503251 ],
       [0.61504925, 0.14653775, 0.238413  ],
       [0.42395743, 0.2072837 , 0.36875887],
       [0.39310294, 0.37352906, 0.233368  ],
       [0.24075936, 0.50345956, 0.25578108],
       [0.37843144, 0.3465974 , 0.27497116],
       [0.54419043, 0.17188637, 0.28392321],
       [0.48253264, 0.21899365, 0.29847371],
       [0.18395391, 0.60919058, 0.2068555 ],
       [0.59134831, 0.14504549, 0.2636062 ],
       [0.72859507, 0.13653457, 0.13487036],
       [0.1487761 , 0.618681  , 0.23254289],
       [0.46028409, 0.32756199, 0.21215392],
       [0.27346799, 0.46841794, 0.25811408],
       [0.7403086 , 0.11915498, 0.14053643],
       [0.

In [10]:
#Vamos con las estadísticas pre-partido


In [12]:
X2=resultado.copy()
X2.drop(columns=["quiniela",'G_esp_local', 'G_esp_visitante',
       'quiniela', 'Posesión_local', 'Posesión_visitante',
       'Pases_intento_local', 'Pases_buenos_local', 'Pases_%_local',
       'Pases_intento_visitante', 'Pases_buenos_visitante',
       'Pases_%_visitante', 'Disparos_puerta_intento_local',
       'Disparos_puerta_buenos_local', 'Disparos_puerta_%_local',
       'Disparos_puerta_intento_visitante', 'Disparos_puerta_buenos_visitante',
       'Disparos_puerta_%_visitante', 'Paradas_local', 'Paradas_%_local',
       'Paradas_visitante', 'Paradas_%_visitante', 'Amarillas_local',
       'expulsion_doble_amarilla_local','expulsión_roja_directa_local', 'Amarillas_visitante',
       'expulsion_doble_amarilla_visitante',
       'expulsión_roja_directa_visitante', 'Faltas_local', 'Faltas_visitante',
       'Saques_esquina_local', 'Saques_esquina_visitante',
       'Pases_cruzados_local', 'Pases_cruzados_visitante', 'Toques_local',
       'Toques_visitante', 'Derribos_local', 'Derribos_visitante',
       'Intercepciones_local', 'Intercepciones_visitante',
       'Duelos_aereos_ganados_local', 'Duelos_aereos_ganados_visitante',
       'Despejes_local', 'Despejes_visitante', 'Fuera_juego_local',
       'Fuera_juego_visitante', 'Saque_puerta_local', 'Saque_puerta_visitante',
       'Saque_banda_local','Saque_banda_visitante', 'Pelotazos_local', 'Pelotazos_visitante','Árbitro_faltas_local',
       'Árbitro_faltas_visitante', 'Árbitro_amarillas_local',
       'Árbitro_amarillas_visitante', 'Árbitro_doble_amarilla_local',
       'Árbitro_doble_amarilla_visitante', 'Árbitro_roja_directa_local',
       'Árbitro_roja_directa_visitante', 'tarjetas_total_local',
       'tarjetas_total_visitante', 'Árbitro_sum_tarjetas_local',
       'Árbitro_sum_tarjetas_visitante', 'faltas_cometidas_local',
       'faltas_cometidas_visitante', 'faltas_provocadas_local',
       'faltas_provocadas_visitante', 'amarillas_cometidas_local',
       'amarillas_cometidas_visitante', 'amarillas_provocadas_local',
       'amarillas_provocadas_visitante', 'dobles_amarillas_cometidas_local',
       'dobles_amarillas_cometidas_visitante',
       'dobles_amarillas_provocadas_local',
       'dobles_amarillas_provocadas_visitante',
       'rojas_directas_cometida_local', 'rojas_directas_cometida_visitante',
       'rojas_directas_provocadas_local',
       'rojas_directas_provocadas_visitante'],inplace=True)
Y=resultado["quiniela"]

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X2,Y,test_size=0.15,random_state=42)

In [14]:
from sklearn.ensemble import RandomForestClassifier

rnd_clas = RandomForestClassifier(n_estimators=200,
                                 max_leaf_nodes=30,
                                 random_state=42)
rnd_clas.fit(X_train, Y_train)

y_pred_clas = rnd_clas.predict(X_test)
accuracy_score(Y_test, y_pred_clas)

0.3958333333333333

In [15]:
#Parece que sale mejor obviando al árbitro

In [16]:
jornada_32=pd.read_csv("jornada32.csv")

In [17]:
#Entreno el modelo con toda la data
rnd_clas2 = RandomForestClassifier(n_estimators=200,
                                 max_leaf_nodes=30,
                                 random_state=42)
rnd_clas2.fit(X2, Y)

y_pred_clas = rnd_clas.predict(X2)
accuracy_score(Y, y_pred_clas)

0.76875

In [18]:
#Predicción entrenando con la data Train
rnd_clas.predict(jornada_32)

array(['2', '2', '1', '1', '1', '1', '1', '2', 'X', '2'], dtype=object)

In [19]:
rnd_clas.predict_proba(jornada_32)

array([[0.17989395, 0.74710665, 0.0729994 ],
       [0.26053497, 0.54150921, 0.19795582],
       [0.87722517, 0.05158558, 0.07118925],
       [0.779298  , 0.09177186, 0.12893015],
       [0.53689199, 0.27448432, 0.1886237 ],
       [0.67573693, 0.1442909 , 0.17997217],
       [0.52575152, 0.16800599, 0.30624249],
       [0.2403239 , 0.58839876, 0.17127734],
       [0.28745294, 0.22702526, 0.4855218 ],
       [0.32694485, 0.42455422, 0.24850093]])

In [20]:
#Predicción entrenando con toda la data
rnd_clas2.predict(jornada_32)

array(['2', '2', '1', '1', '1', '1', '1', '2', 'X', '2'], dtype=object)

In [21]:
rnd_clas2.predict_proba(jornada_32)

array([[0.24796272, 0.67998025, 0.07205703],
       [0.26219891, 0.53673725, 0.20106383],
       [0.8506912 , 0.05209719, 0.09721161],
       [0.74512576, 0.09346605, 0.16140819],
       [0.48220543, 0.26499602, 0.25279855],
       [0.5805408 , 0.21078673, 0.20867247],
       [0.40965958, 0.23941369, 0.35092673],
       [0.2280417 , 0.60095876, 0.17099954],
       [0.30382524, 0.25843725, 0.43773751],
       [0.32750478, 0.36543054, 0.30706467]])

In [22]:
#Voy a ver si saco el mejor RandomForest
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Definir el modelo a utilizar
rfc = RandomForestClassifier()



In [23]:
# Definir los parámetros a ajustar
param_grid = {
    'n_estimators': [100, 200, 500],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt']
}

# Realizar el GridSearchCV
grid_search = GridSearchCV(estimator = rfc, param_grid = param_grid, 
                          cv = 5, n_jobs = -1, verbose = 2)

In [24]:
grid_search.fit(X2, Y)

Fitting 5 folds for each of 162 candidates, totalling 810 fits


GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [None, 5, 10],
                         'max_features': ['auto', 'sqrt'],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 500]},
             verbose=2)

In [25]:
grid_search.best_estimator_

RandomForestClassifier(max_depth=5, min_samples_leaf=2, min_samples_split=10)

In [26]:
rnd_clas3 = RandomForestClassifier(max_depth=5, max_features='sqrt', min_samples_leaf=2,
                       min_samples_split=5, n_estimators=500)
rnd_clas3.fit(X2, Y)



RandomForestClassifier(max_depth=5, max_features='sqrt', min_samples_leaf=2,
                       min_samples_split=5, n_estimators=500)

In [27]:
#Con los parámetros optimizados
rnd_clas3.predict(jornada_32)

array(['2', '2', '1', '1', '1', '1', '1', '2', 'X', '1'], dtype=object)

In [28]:
rnd_clas3.predict_proba(jornada_32)

array([[0.24725192, 0.63302762, 0.11972045],
       [0.26940151, 0.48145947, 0.24913903],
       [0.8755299 , 0.04885343, 0.07561667],
       [0.70406112, 0.11301835, 0.18292053],
       [0.44391837, 0.26698181, 0.28909982],
       [0.60470763, 0.18084711, 0.21444526],
       [0.39154229, 0.2629939 , 0.34546382],
       [0.24097046, 0.54951046, 0.20951909],
       [0.34820251, 0.23566417, 0.41613331],
       [0.39971032, 0.3213994 , 0.27889028]])

Predicción J.33

In [29]:
jornada_33=pd.read_csv("jornada33_resultados.csv")

In [30]:
rnd_clas2.predict(jornada_33)

array(['1', '2', '1', '1', '1', '1', '1', '2', '1', '1'], dtype=object)

In [31]:
rnd_clas2.predict_proba(jornada_33)

array([[0.53585948, 0.19134454, 0.27279598],
       [0.38430463, 0.41747436, 0.19822101],
       [0.65772594, 0.17711139, 0.16516267],
       [0.50215641, 0.27821429, 0.2196293 ],
       [0.51431547, 0.34013914, 0.14554539],
       [0.55873031, 0.24023377, 0.20103592],
       [0.4492394 , 0.38788551, 0.16287509],
       [0.34408703, 0.38577095, 0.27014202],
       [0.44315701, 0.29595159, 0.2608914 ],
       [0.58635501, 0.20824236, 0.20540263]])

In [32]:
import pickle

filename = 'resultados_model.pkl'

with open(filename, 'wb') as archivo_salida:
    pickle.dump(rnd_clas2, archivo_salida)