In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
tarjetas=pd.read_csv("data/datas limpias/3/data_tarjetas2.csv")

In [11]:
#Primero el equipo local, viendo estadísticas del partido

In [3]:
X=tarjetas[["clas_local","clas_visitante","Faltas_local","Derribos_local",
            'Árbitro_sum_tarjetas_local','tarjetas_cometidas_local','tarjetas_provocadas_visitante']]
Y=tarjetas["tarjetas_total_local"]

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.15,random_state=42)

In [5]:
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score,mean_absolute_error

In [6]:
rnd_clas = RandomForestRegressor(n_estimators=200,
                                 max_leaf_nodes=30,
                                 random_state=42)
rnd_clas.fit(X_train, Y_train)

y_pred_clas = rnd_clas.predict(X_test)
mean_absolute_error(Y_test, y_pred_clas)

1.3603289591074859

In [7]:
Y_test

167    3
230    0
25     1
63     3
9      3
110    5
186    1
143    0
244    2
224    6
90     5
76     4
82     3
240    5
172    3
119    0
202    4
77     5
55     8
104    2
203    2
211    3
198    0
139    3
42     4
213    5
297    4
33     5
73     4
183    1
75     1
5      3
168    4
157    3
300    1
78     2
176    2
284    1
222    3
84     0
7      0
193    3
285    3
281    1
46     3
3      4
260    8
194    3
Name: tarjetas_total_local, dtype: int64

In [8]:
y_pred_clas

array([1.08215304, 3.0405455 , 1.9326072 , 3.8144368 , 1.44276557,
       4.3380715 , 1.69229675, 2.17919648, 1.82166176, 3.89316038,
       5.13058302, 3.68985009, 2.02400454, 2.85563291, 4.41399141,
       3.10879288, 3.59125172, 3.52394946, 3.19541609, 2.51913451,
       3.41800738, 2.27055123, 1.36757894, 2.06206242, 3.26064526,
       3.18157405, 2.2815947 , 3.49203075, 4.58144744, 2.5695787 ,
       1.378664  , 2.9026922 , 2.37128597, 4.00413731, 2.45459154,
       3.25362054, 3.19937443, 2.58911109, 4.23957417, 1.95132022,
       1.91710058, 2.63370891, 0.99167309, 1.27406384, 2.58399966,
       3.23223182, 3.55634865, 1.45564894])

In [ ]:
#Ahora las visitantes

In [9]:
X2=tarjetas[["clas_local","clas_visitante","Faltas_visitante","Derribos_visitante",
            'Árbitro_sum_tarjetas_visitante','tarjetas_cometidas_visitante','tarjetas_provocadas_local']]
Y2=tarjetas["tarjetas_total_visitante"]

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X2,Y2,test_size=0.15,random_state=42)

In [11]:
rnd_clas2 = RandomForestRegressor(n_estimators=200,
                                 max_leaf_nodes=30,
                                 random_state=42)
rnd_clas2.fit(X_train, Y_train)

y_pred_clas = rnd_clas2.predict(X_test)
mean_absolute_error(Y_test, y_pred_clas)

1.5892813658399643

In [ ]:
#Vamos con las estadísticas pre-partido

In [ ]:
#Local

In [12]:
X3=tarjetas[["clas_local","clas_visitante","Árbitro_sum_tarjetas_local","faltas_cometidas_local","faltas_provocadas_visitante","tarjetas_cometidas_local",
             'Árbitro_faltas_local',"tarjetas_provocadas_visitante"]]
Y3=tarjetas["tarjetas_total_local"]

In [13]:
X_train,X_test,Y_train,Y_test=train_test_split(X3,Y3,test_size=0.15,random_state=42)

In [14]:
rnd_clas3 = RandomForestRegressor(n_estimators=200,
                                 max_leaf_nodes=30,
                                 random_state=42)
rnd_clas3.fit(X_train, Y_train)
y_pred_clas = rnd_clas3.predict(X_test)
mean_absolute_error(Y_test, y_pred_clas)

1.42020917275209

In [103]:
Y_test

289    3
9      3
57     0
60     1
25     1
63     3
92     3
184    4
244    2
46     3
75     1
163    2
296    3
307    0
285    3
290    4
5      3
155    1
164    5
168    4
73     4
104    2
137    7
206    1
76     4
173    1
113    6
33     5
275    3
251    1
108    2
3      4
82     3
259    4
93     1
101    2
45     3
17     2
197    4
119    0
42     4
24     5
179    2
242    4
298    2
196    1
226    1
Name: tarjetas_total_local, dtype: int64

In [15]:
y_pred_clas

array([1.04396991, 2.68738284, 1.84093607, 4.09070139, 1.66898996,
       4.1107045 , 1.88774805, 2.55271349, 1.63091412, 4.12554171,
       4.09596311, 3.44040704, 2.1061704 , 2.97992973, 4.0907818 ,
       3.70665432, 3.02103407, 2.57885562, 3.25134481, 2.95663625,
       4.19997734, 2.69219774, 1.82771664, 2.73863623, 3.84279894,
       2.43182843, 1.80478964, 3.01132726, 4.21981432, 2.50786753,
       1.36005086, 2.52665607, 1.93980967, 3.78955068, 2.46025823,
       2.97892523, 2.02013196, 2.87005815, 2.5503555 , 1.62814362,
       1.50741066, 2.04355229, 1.09994374, 1.43314107, 2.55859544,
       2.61438299, 3.22869243, 2.30916885])

In [ ]:
#Prepartido visitante

In [16]:
X4=tarjetas[["clas_local","clas_visitante","Árbitro_sum_tarjetas_visitante","faltas_cometidas_visitante","faltas_provocadas_local","tarjetas_cometidas_visitante",
             'Árbitro_faltas_visitante',"tarjetas_provocadas_local"]]
Y4=tarjetas["tarjetas_total_visitante"]

In [17]:
X4

clas_local  clas_visitante  Árbitro_sum_tarjetas_visitante  \
0             3               3                        2.222222   
1             3               2                        2.857143   
2             2               4                        1.470588   
3             5               3                        3.933333   
4             2               4                        2.928571   
..          ...             ...                             ...   
315           4               3                        3.647059   
316           2               2                        3.222222   
317           2               5                        3.111111   
318           3               4                        3.823529   
319           3               3                        3.625000   

     faltas_cometidas_visitante  faltas_provocadas_local  \
0                     11.937500                12.250000   
1                     12.125000                13.250000   
2                     11.062500                13.687500   
3                     15.875000                11.937500   
4                     16.470588                12.647059   
..                          ...                      ...   
315                   11.875000                13.937500   
316                   14.500000                14.750000   
317                   12.937500                13.687500   
318                   13.750000                13.875000   
319                   11.687500                13.500000   

     tarjetas_cometidas_visitante  Árbitro_faltas_visitante  \
0                        3.937500                 12.333333   
1                        3.000000                 11.928571   
2                        2.250000                 12.705882   
3                        2.875000                 12.800000   
4                        2.294118                 13.000000   
..                            ...                       ...   
315                      2.437500                 15.000000   
316                      3.500000                 14.777778   
317                      3.125000                 13.888889   
318                      2.187500                 14.764706   
319                      2.750000                 13.250000   

     tarjetas_provocadas_local  
0                     2.937500  
1                     3.000000  
2                     2.062500  
3                     3.250000  
4                     2.705882  
..                         ...  
315                   3.750000  
316                   3.125000  
317                   2.062500  
318                   3.312500  
319                   2.812500  

[320 rows x 8 columns]

In [18]:
X_train,X_test,Y_train,Y_test=train_test_split(X4,Y4,test_size=0.15,random_state=42)

In [19]:
rnd_clas4 = RandomForestRegressor(n_estimators=500,
                                 max_leaf_nodes=30,
                                 max_depth=4,
                                 random_state=42)
rnd_clas4.fit(X_train, Y_train)
y_pred_clas = rnd_clas4.predict(X_test)
mean_absolute_error(Y_test, y_pred_clas)

1.6517264038525667

In [73]:
#Voy a entrenar ambos modelos con la data completa

In [20]:
df_tarjetas_local=pd.read_csv("jornada32_tarjetas_local.csv")

In [21]:
rnd_clas3 = RandomForestRegressor(n_estimators=200,
                                 max_leaf_nodes=30,
                                 random_state=42)
rnd_clas3.fit(X3, Y3)
rnd_clas3.predict(df_tarjetas_local)

array([2.60579796, 2.40801484, 2.02740693, 1.60560861, 2.48748073,
       3.10294509, 2.94463952, 2.47965356, 3.9366044 , 3.10861817])

In [22]:
df_tarjetas_visitante=pd.read_csv("jornada32_tarjetas_visitante.csv")

In [23]:
rnd_clas4 = RandomForestRegressor(n_estimators=500,
                                 max_leaf_nodes=30,
                                 max_depth=4,
                                 random_state=42)
rnd_clas4.fit(X4, Y4)
rnd_clas4.predict(df_tarjetas_visitante)

array([3.17177645, 3.33828582, 3.00436725, 3.22598222, 2.82838293,
       3.35639468, 3.95673215, 2.9608425 , 2.79888978, 3.14318194])

Predicción J.33

In [24]:
df_tarjetas_local=pd.read_csv("jornada33_tarjetas_local.csv")

In [25]:
rnd_clas3 = RandomForestRegressor(n_estimators=200,
                                 max_leaf_nodes=30,
                                 random_state=42)
rnd_clas3.fit(X3, Y3)
rnd_clas3.predict(df_tarjetas_local)

array([1.13939408, 2.81180291, 2.83476652, 1.65562664, 1.91562864,
       3.10728202, 2.7938889 , 3.45035973, 3.63058049, 2.83764551])

In [26]:
df_tarjetas_visitante=pd.read_csv("jornada33_tarjetas_visitante.csv")

In [27]:
rnd_clas4 = RandomForestRegressor(n_estimators=500,
                                 max_leaf_nodes=30,
                                 max_depth=4,
                                 random_state=42)
rnd_clas4.fit(X4, Y4)
rnd_clas4.predict(df_tarjetas_visitante)

array([4.15709575, 2.40188118, 3.92405032, 3.78747434, 2.7031622 ,
       3.9627051 , 3.41142128, 2.56166575, 3.39661485, 3.62623928])

In [28]:
import pickle

filename4 = 'tarjetas_local_model.pkl'

with open(filename4, 'wb') as archivo_salida:
    pickle.dump(rnd_clas3, archivo_salida)

In [29]:
filename5 = 'tarjetas_visitante_model.pkl'

with open(filename5, 'wb') as archivo_salida:
    pickle.dump(rnd_clas4, archivo_salida)